### ISSUE TITLE
No accent folding?

### ISSUE THREAD

**Issue by gabssnake** [Zinggi/DictionaryAutoComplete#12]
English is pretty exceptional in not requiring any accents. German, French, Spanish, they all require accents. But it seems that currently the plugin does no accent folding (it does case folding however).

For the plugin to _work_ with languages besides English, “Théâtre” (note the accents) should be suggested when writing “Theatre” (note the absence of accents) if the proper dictionary is installed (French in this case). In other words, it has to do some degree of accent folding, otherwise it is not really useful as autocompletion in those languages.

Looking through the source, it seems like there is some case folding already going on in `get_autocomplete_list` on line 59: `if word.lower() in w.lower() :`. So might be as easy as swapping `.lower()` with an accent folding function. Google suggested [`unidecode`](https://pypi.python.org/pypi/Unidecode/0.04.1). I suppose the words collection could be stored in a hash-like structure with the folded word as key and the real world as value for better performance, somewhere in `load_completions`.

 But then again, I know squat about Python :)

**Comment by kpym** [comment]
New setting `smash characters` is added in eb99e0b9d027d80fbf54788ce2df75a299e810da. It allows you to identify characters with accents in some languages. For example for french you can set
  ```
  "smash characters": ["eéèêë", "aàâä", "cç", "iîï", "oôö", "uùûü", "yÿ"]
  ```
  and then when you type "lecon" it will suggest you "leçon".

It is based on `translate` python method for strings.

You can check [DictionaryAutoComplete.sublime-settings](https://github.com/Zinggi/DictionaryAutoComplete/blob/eb99e0b9d027d80fbf54788ce2df75a299e810da/DictionaryAutoComplete.sublime-settings) to see how to use it.
