### ISSUE TITLE
How to change hotkey

### ISSUE THREAD

**Issue by iRet** [Zinggi/DictionaryAutoComplete#15]
Is it possible to change Ctrl+Space combination to something another in config?
This one is already bound in OSX to spotlight.

**Comment by Zinggi** [comment]
Im on holidays, so i cant veryfy my answer, but i think it's as easy as adding the corresponding keybind to your sublime keybindings file.
Please consult the official sublime documentation if you don't know how to do that. Hope that helps.

**Comment by Zinggi** [comment]
I'm closing this, as this is not a DictionaryAutoComplete issue, but a Sublime Text issue
