### ISSUE TITLE
I can't use DictionaryAutoComplete when input string.

### ISSUE THREAD

**Issue by Andrew-liu** [Zinggi/DictionaryAutoComplete#16]
I have entry to my 'Settings - User' with setting. such as below:

```python
{
    "auto_complete_selector": "source, text"
}
```

but, When I restart sublime, it hasn't any change.

**Comment by Zinggi** [comment]
Doesn't seem to be caused by my plugin at first sight, seems to be an issue with sublime. However I can't investigate now as I'm on holidays.

**Comment by Andrew-liu** [comment]
Thank you for your reply, I am so pity to fail to use it.

> otherwise,  Have a nice hay!
