### ISSUE TITLE
Minimum required length until auto completion starts

### ISSUE THREAD

**Issue by LukasKalbertodt** [Zinggi/DictionaryAutoComplete#20]
Maybe its not really useful to already show suggestions after one or two types chars. This should be configurable in the settings. Just an idea...

**Comment by Zinggi** [comment]
Thats a good idea and it would certainly improve the plugin, however I'm not actively developing the plugin anymore.
So I'm not gonna implement anything new.

If you would like to implement it yourself, I'll happily accept a pull request.

**Comment by kpym** [comment]
Done in 3981b5772c9cf37c03d83c453a7014d92c502c9c.
