### ISSUE TITLE
Feature request: add addtiional keystroke gutter in the dropdown menu

### ISSUE THREAD

**Issue by duytrung** [Zinggi/DictionaryAutoComplete#21]
Hi,
I think that it would be better if you add the numbering or character navigation for the dropdown menu for example, I puting in "type"
typ
=========================================
1.type
2.typeahead
3.typecast
4.typedef
5...
..
0..
F1. 
F2. 
F3....
=========================================

this should appear alike DiCOM or PhraseExpress program behaviors which are not available on linux.
Basically from 1-0, F1 - F12, we have ability to navigate through 22 option in the dropdown menu faster than normal a little bit. I know sublimetext has shortcuts but sometime not convenient in these cases.

As above if I want to type "typeahead", i can press "2".

Thanks for considering this request.

TN

**Comment by Zinggi** [comment]
Thanks for the suggestion. Unfortunately the Sublime Text plugin API is very limited, so I'm pretty sure that implementing your suggestion wouldn't be possible. That is, it would be pretty simple to display the numbers, but navigating by any other means than the built-in wouldn't work.

Besides, your suggestion seems like a very slow way of navigating the suggestions, as opposed to just keep typing to narrow down the suggestions and navigating them using the up and down keys.

So I wont be able to implement this.

Cheers
