### ISSUE TITLE
[Feature request] Disable autocomplete after colons

### ISSUE THREAD

**Issue by Kristinita** [Zinggi/DictionaryAutoComplete#22]
I use [Github-Emoji](https://github.com/akatopo/GithubEmoji) plugin. After I wrote `:`, in the auto complete options appear emoticons. But DictionaryAutoComplete autocomplete variants that prevent me preview emoticons. I think, will be good, if you added option `disable_after_colon`.

Thanks.

**Comment by Zinggi** [comment]
That sounds like a useful addition if you're using some conflicting plugin.
However, I'm not actively developing this plugin anymore, as I'm not using it myself.

I'd happily accept a pull request though, so if you'd like to implement that yourself, go ahead.   
If you do, I think it would be best if it was a bit more general, e.g. a setting `disable_if_matches_regex` with default `"a^"`, as this would never match anything.
Then you could have your desired behavior by setting it to `"^:"` to get your desired behavior.

**Comment by kpym** [comment]
The settings option `forbidden prefixes` was added in 49abb19bd5c17148710b43befd57e3664569faf2.
