### ISSUE TITLE
Question: where is the dictionary

### ISSUE THREAD

**Issue by neilsustc** [Zinggi/DictionaryAutoComplete#24]
Nice extension, I'd like to port it to vscode. But I can't find the dictionary. Where can I find it?

**Comment by Zinggi** [comment]
There is no dictionary included in this package, this extension just uses the dictionary [sublime uses for spellchecking](https://www.sublimetext.com/docs/3/spell_checking.html).

So if you're just looking for dictionaries, you should probably look [here](https://github.com/titoBouzout/Dictionaries).

*(closing this, as it's just a question)*

**Comment by neilsustc** [comment]
Thanks
