### ISSUE TITLE
Only add dictionary entries on specific syntaxes

### ISSUE THREAD

**Issue by eivind88** [Zinggi/DictionaryAutoComplete#25]
Is there any way to make this plug-in only add dictionary entries to the completions on specific syntaxes?

I find DictionaryAutoComplete very useful, but I tend not to really need it when editing source files, as opposed to documentation (e.g. Markdown, Plain Text).

**Comment by Zinggi** [comment]
Hey, Im currently on holidays, so i cant easily look stuff up, but I believe you can easily do that in the syntax specific settings file by playing around with the auto_complete_selector setting. 
This might help: https://www.sublimetext.com/docs/3/settings.html

Let me know if that works

**Comment by eivind88** [comment]
Wouldn't changing the `auto_complete_selector` change where the autocompletion is triggered in general, as opposed to the contents of it?

What I'm after is some way to not add dictionary completions to my autocompletions when editing source files.

**Comment by Zinggi** [comment]
Ah ok, now i understood. 
It already shouldn't trigger when editing source files, only inside comments and inside strings. 

It would be easy to implement a more customizable way, e.g. controlled inside the settings file.

However, I'm not actively developing this plugin anymore, but I'm open to any pull request.
So if you want to make it more customizable, the relevant lines are here: https://github.com/Zinggi/DictionaryAutoComplete/blob/master/DictionaryAutoComplete.py#L72

**Comment by eivind88** [comment]
It seems that I wasn't diligent enough in trying to trace the culprit;
I had another plugin installed (that I had forgotten about) that caused the problem.

DictionaryAutoComplete works as you state.

Sorry about that!

**Comment by Zinggi** [comment]
No worries, I'm glad it works for you
