### ISSUE TITLE
launch error

### ISSUE THREAD

**Issue by mugsuk** [Zinggi/DictionaryAutoComplete#29]
I have installed the package and each time I launch Sublime Text the following error message is thrown up:

"Error trying to parse settings: Unexpected character, expected a comma or closing bracket in Packages/User/DictionaryAutoComplete.sublime-settings:3:4"

I have not made any changes to this file.

The functionality after dismissing the error is good, i.e the package works as expected, but it is annoying to have the error message pop-up each time and I was wondering if there is a simple fix.

Thanks for your time

Murray

**Comment by kpym** [comment]
Could you post your `DictionaryAutoComplete.sublime-settings` here.

The error is on line 3, but the line 3 in the default [DictionaryAutoComplete.sublime-settings](https://github.com/Zinggi/DictionaryAutoComplete/blob/master/DictionaryAutoComplete.sublime-settings#L3) is a comment. 🤔

**Comment by mugsuk** [comment]
I am soooooo sorry for wasting your time - I was looking at the default setting file, not the user setting. I realise that I had created a syntactical error in the user setting file and I have fixed it. Thank you for an amazing piece of software
