### ISSUE TITLE
Error when opening SLT

### ISSUE THREAD

**Issue by wxguy** [Zinggi/DictionaryAutoComplete#30]
Thank you for the excellent and much needed plugin. I get following error when I open SLT:-

```python
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 923, in on_modified_async
    run_view_callbacks('on_modified_async', view_id)
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 708, in run_view_callbacks
    callback(v, *args)
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 190, in exception_handler
    return event_handler(*args)
  File "/home/sundar/.config/sublime-text/Installed Packages/DictionaryAutoComplete.sublime-package/DictionaryAutoComplete.py", line 327, in on_modified_async
    if not plugin_is_active:
NameError: global name 'plugin_is_active' is not defined
``

Help to solve the issue is appreciated.

**Comment by wxguy** [comment]
Thank you for the fix. The PC does not seems to sync at the moment. Will update when it is available and get back. Or else, if you know how to update without PC, please share.

**Comment by wxguy** [comment]
Ok. Got it working. Removed the package from PC and cloned the repo. I can confirm that the plugin works fine.

Just curious that why do you stick to SLT's Python version 3.3 whereas they have updated it to 3.8.

**Comment by kpym** [comment]
> Just curious that why do you stick to SLT's Python version 3.3 whereas they have updated it to 3.8. 

Probably because the last commit was 5 years ago 😁

Where have you seen version 3.3 mentioned?

**Comment by wxguy** [comment]
> Where have you seen version 3.3 mentioned?

https://www.sublimetext.com/docs/api_environments.html.

> Starting in build 4050, plugins may also be run using Python 3.8. Python 3.8 features many improvements to the language, better performance and continued support and bug fixes from the Python Software Foundation.

The specific error reported in
https://github.com/Zinggi/DictionaryAutoComplete/issues/30#issue-2573603187 has the python path having `python33`.
